version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yggdrasil-php
    working_dir: /var/www/html/yggdrasil
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: yggdrasil-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yggdrasil
      MYSQL_USER: yggdrasil
      MYSQL_PASSWORD: yggdrasil
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
